### ISSUE TITLE
TypeError: Cannot read property 'encrypt' of undefined

### ISSUE THREAD

**Issue by iamgruuten** [yjs/y-webrtc#26]
**Describe the bug**
I was trying to disconnect and connect the room but encounter an error
```
TypeError: Cannot read property 'encrypt' of undefined
Module.encrypt

  49 |   return /** @type {PromiseLike<Uint8Array>} */ (promise.resolve(data))
  50 | }
  51 | const iv = crypto.getRandomValues(new Uint8Array(12))
> 52 | return crypto.subtle.encrypt(
     | ^  53 |   {
  54 |     name: 'AES-GCM',
  55 |     iv
```

**To Reproduce**
1. attempts to disconnect room
2. attempts to destroy room 
3. Error produced

**Expected behavior**
It should properly destroy the room 

**Environment Information**
 - Chrome
 - yjs v13.5.5, y-webrtc v10.2.0

**Comment by dmonad** [comment]
Are you destroying a room and then reconnecting?

I don't want to play guessing games. These details are insufficient. I asked for your browser version specifically.

**Comment by dmonad** [comment]
Please feel free to open a new ticket where you explain what exactly you do.
