### ISSUE TITLE
[Question] Can we add or remove signaling servers dynamically?

### ISSUE THREAD

**Issue by KiddoV** [yjs/y-webrtc#67]
Hi, I have a question regarding the use of dynamic signaling servers with the WebrtcProvider. Is there a way to add or remove signaling servers dynamically after initializing the provider?

Specifically, I’m wondering if it’s possible to switch signaling servers or handle errors with the signaling connection by adding/removing servers without reinitializing the entire WebrtcProvider or its awareness instance.

Thanks!

**Comment by KiddoV** [comment]
So that's a "NO," I suppose.

**Comment by dmonad** [comment]
In the issue template I politely asked not to use this issue tracker as a discussion board.. Apparantly you didn't read it. 

Please help me to me more efficient by following the rules. I think that's a small favor to ask for.
