### ISSUE TITLE
Add simple-peer config

### ISSUE THREAD

**Issue by holtwick** [yjs/y-webrtc#8]
It would be nice to have a way to set the config for the peers like custom STUN and TURN servers. I added `peerSettings` here to `y-webrtc.js` to pass it through to `Peer`:

https://github.com/holtwick/peer2school/blob/develop/src/lib/y-webrtc.js

**Comment by dmonad** [comment]
Done. I implemented `peerOpts` and updated the README.

**Comment by holtwick** [comment]
Thanks!
